#!/bin/bash
stalonetray &>/dev/null &
parcellite &>/dev/null &
nm-applet &>/dev/null &
xscreensaver &>/dev/null &
[[ -f /home/fila/.xmodmap ]] && /usr/bin/xmodmap /home/fila/.xmodmap > /home/fila/.xmodmap.log 2>&1
# xsetroot -solid black
# corebird &>/dev/null &
xhost si:localuser:root
setxkbmap -layout \"us,cz\" -option grp:lctrl_lshift_toggle
dunst &>/dev/null &
picom -CGb
